package:
  name: multimds
  version: "0.0.3"

source:
#  git_rev: v0.6.7
  git_url: https://github.com/seqcode/multimds.git
#   url: https://files.pythonhosted.org/packages/79/d6/0aebf673a9391aab8aecf0a81f80312b1dd296b0da4ad6ce47eee662a0ab/multimds-0.0.3.tar.gz
#   sha256: b3702aad48bbf1d0f41c6cf0500f2857d45a159711c7bf27bf30525ba68ba701

requirements:
  build:
    - python
    - setuptools
    - scipy
    - numpy
#    - pymp-pypi
    - mayavi
    - scikit-learn
    - h5py
    - pandas
    - seaborn

  run:
    - python

test:
  imports: 
    - multimds

about:
  home: https://github.com/seqcode/multimds
