package:
  name: multimds
  version: "0.0.1"

source:
#  git_rev: v0.6.7
  git_url: https://github.com/seqcode/multimds.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports: 
    - multimds

about:
  home: https://github.com/seqcode/multimds
